/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TagorClient.Client.OpenAPIDateConverter;

namespace TagorClient.Model
{
    /// <summary>
    /// DsTDOSAFBDETWebDsTDOSAFBDETWebTtTDOSAFBDETWebInner
    /// </summary>
    [DataContract(Name = "dsTDOSAFBDETWeb_dsTDOSAFBDETWeb_ttTDOSAFBDETWeb_inner")]
    public partial class DsTDOSAFBDETWebDsTDOSAFBDETWebTtTDOSAFBDETWebInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DsTDOSAFBDETWebDsTDOSAFBDETWebTtTDOSAFBDETWebInner" /> class.
        /// </summary>
        /// <param name="tDOSAFBId">tDOSAFBId.</param>
        /// <param name="bedrag">bedrag.</param>
        /// <param name="datumBetaal">datumBetaal.</param>
        /// <param name="datumTot">datumTot.</param>
        /// <param name="tQPERIODEId">tQPERIODEId.</param>
        /// <param name="sequenceId">sequenceId.</param>
        /// <param name="bedrag1stePeriode">bedrag1stePeriode.</param>
        /// <param name="datum1stePeriode">datum1stePeriode.</param>
        public DsTDOSAFBDETWebDsTDOSAFBDETWebTtTDOSAFBDETWebInner(string tDOSAFBId = default(string), string bedrag = default(string), DateOnly datumBetaal = default(DateOnly), DateOnly datumTot = default(DateOnly), string tQPERIODEId = default(string), string sequenceId = default(string), string bedrag1stePeriode = default(string), DateOnly datum1stePeriode = default(DateOnly))
        {
            this.TDOSAFBId = tDOSAFBId;
            this.Bedrag = bedrag;
            this.DatumBetaal = datumBetaal;
            this.DatumTot = datumTot;
            this.TQPERIODEId = tQPERIODEId;
            this.SequenceId = sequenceId;
            this.Bedrag1stePeriode = bedrag1stePeriode;
            this.Datum1stePeriode = datum1stePeriode;
        }

        /// <summary>
        /// Gets or Sets TDOSAFBId
        /// </summary>
        [DataMember(Name = "TDOSAFB_Id", EmitDefaultValue = false)]
        public string TDOSAFBId { get; set; }

        /// <summary>
        /// Gets or Sets Bedrag
        /// </summary>
        [DataMember(Name = "Bedrag", EmitDefaultValue = false)]
        public string Bedrag { get; set; }

        /// <summary>
        /// Gets or Sets DatumBetaal
        /// </summary>
        [DataMember(Name = "DatumBetaal", EmitDefaultValue = false)]
        public DateOnly DatumBetaal { get; set; }

        /// <summary>
        /// Gets or Sets DatumTot
        /// </summary>
        [DataMember(Name = "DatumTot", EmitDefaultValue = false)]
        public DateOnly DatumTot { get; set; }

        /// <summary>
        /// Gets or Sets TQPERIODEId
        /// </summary>
        [DataMember(Name = "TQPERIODE_Id", EmitDefaultValue = false)]
        public string TQPERIODEId { get; set; }

        /// <summary>
        /// Gets or Sets SequenceId
        /// </summary>
        [DataMember(Name = "Sequence_Id", EmitDefaultValue = false)]
        public string SequenceId { get; set; }

        /// <summary>
        /// Gets or Sets Bedrag1stePeriode
        /// </summary>
        [DataMember(Name = "Bedrag1stePeriode", EmitDefaultValue = false)]
        public string Bedrag1stePeriode { get; set; }

        /// <summary>
        /// Gets or Sets Datum1stePeriode
        /// </summary>
        [DataMember(Name = "Datum1stePeriode", EmitDefaultValue = false)]
        public DateOnly Datum1stePeriode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DsTDOSAFBDETWebDsTDOSAFBDETWebTtTDOSAFBDETWebInner {\n");
            sb.Append("  TDOSAFBId: ").Append(TDOSAFBId).Append("\n");
            sb.Append("  Bedrag: ").Append(Bedrag).Append("\n");
            sb.Append("  DatumBetaal: ").Append(DatumBetaal).Append("\n");
            sb.Append("  DatumTot: ").Append(DatumTot).Append("\n");
            sb.Append("  TQPERIODEId: ").Append(TQPERIODEId).Append("\n");
            sb.Append("  SequenceId: ").Append(SequenceId).Append("\n");
            sb.Append("  Bedrag1stePeriode: ").Append(Bedrag1stePeriode).Append("\n");
            sb.Append("  Datum1stePeriode: ").Append(Datum1stePeriode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
