/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TagorClient.Client.OpenAPIDateConverter;

namespace TagorClient.Model
{
    /// <summary>
    /// TagorServicePaymentInfo200ResponseResponse
    /// </summary>
    [DataContract(Name = "TagorServicePaymentInfo_200_response_response")]
    public partial class TagorServicePaymentInfo200ResponseResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TagorServicePaymentInfo200ResponseResponse" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="error">error.</param>
        /// <param name="betaalplan">Indicates whether there is a paymentplan..</param>
        /// <param name="maandbedrag">Agreed monthly amount of current payment plan..</param>
        /// <param name="achterstand">Arrears balance..</param>
        public TagorServicePaymentInfo200ResponseResponse(bool success = default(bool), string error = default(string), bool betaalplan = default(bool), double maandbedrag = default(double), double achterstand = default(double))
        {
            this.Success = success;
            this.Error = error;
            this.Betaalplan = betaalplan;
            this.Maandbedrag = maandbedrag;
            this.Achterstand = achterstand;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "Success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "Error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Indicates whether there is a paymentplan.
        /// </summary>
        /// <value>Indicates whether there is a paymentplan.</value>
        [DataMember(Name = "Betaalplan", EmitDefaultValue = true)]
        public bool Betaalplan { get; set; }

        /// <summary>
        /// Agreed monthly amount of current payment plan.
        /// </summary>
        /// <value>Agreed monthly amount of current payment plan.</value>
        [DataMember(Name = "Maandbedrag", EmitDefaultValue = false)]
        public double Maandbedrag { get; set; }

        /// <summary>
        /// Arrears balance.
        /// </summary>
        /// <value>Arrears balance.</value>
        [DataMember(Name = "Achterstand", EmitDefaultValue = false)]
        public double Achterstand { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TagorServicePaymentInfo200ResponseResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Betaalplan: ").Append(Betaalplan).Append("\n");
            sb.Append("  Maandbedrag: ").Append(Maandbedrag).Append("\n");
            sb.Append("  Achterstand: ").Append(Achterstand).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
