/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using TagorClient.Client;
using TagorClient.Model;

namespace TagorClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDossierlijnApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Dossierlijn/CreateInfoLine
        /// </summary>
        /// <remarks>
        /// Create an info record on a financial record
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DossierlijnCreateInfoLine200Response</returns>
        DossierlijnCreateInfoLine200Response DossierlijnCreateInfoLine(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0);

        /// <summary>
        /// Dossierlijn/CreateInfoLine
        /// </summary>
        /// <remarks>
        /// Create an info record on a financial record
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DossierlijnCreateInfoLine200Response</returns>
        ApiResponse<DossierlijnCreateInfoLine200Response> DossierlijnCreateInfoLineWithHttpInfo(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0);
        /// <summary>
        /// Dossierlijn/DeleteInfoLine
        /// </summary>
        /// <remarks>
        /// Deletes a single info record.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PartyDeleteContactDetail200Response</returns>
        PartyDeleteContactDetail200Response DossierlijnDeleteInfoLine(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0);

        /// <summary>
        /// Dossierlijn/DeleteInfoLine
        /// </summary>
        /// <remarks>
        /// Deletes a single info record.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PartyDeleteContactDetail200Response</returns>
        ApiResponse<PartyDeleteContactDetail200Response> DossierlijnDeleteInfoLineWithHttpInfo(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0);
        /// <summary>
        /// Dossierlijn/GetInfo
        /// </summary>
        /// <remarks>
        /// Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DossierlijnGetInfo200Response</returns>
        DossierlijnGetInfo200Response DossierlijnGetInfo(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0);

        /// <summary>
        /// Dossierlijn/GetInfo
        /// </summary>
        /// <remarks>
        /// Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DossierlijnGetInfo200Response</returns>
        ApiResponse<DossierlijnGetInfo200Response> DossierlijnGetInfoWithHttpInfo(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDossierlijnApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Dossierlijn/CreateInfoLine
        /// </summary>
        /// <remarks>
        /// Create an info record on a financial record
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DossierlijnCreateInfoLine200Response</returns>
        System.Threading.Tasks.Task<DossierlijnCreateInfoLine200Response> DossierlijnCreateInfoLineAsync(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Dossierlijn/CreateInfoLine
        /// </summary>
        /// <remarks>
        /// Create an info record on a financial record
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DossierlijnCreateInfoLine200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<DossierlijnCreateInfoLine200Response>> DossierlijnCreateInfoLineWithHttpInfoAsync(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Dossierlijn/DeleteInfoLine
        /// </summary>
        /// <remarks>
        /// Deletes a single info record.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PartyDeleteContactDetail200Response</returns>
        System.Threading.Tasks.Task<PartyDeleteContactDetail200Response> DossierlijnDeleteInfoLineAsync(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Dossierlijn/DeleteInfoLine
        /// </summary>
        /// <remarks>
        /// Deletes a single info record.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PartyDeleteContactDetail200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<PartyDeleteContactDetail200Response>> DossierlijnDeleteInfoLineWithHttpInfoAsync(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Dossierlijn/GetInfo
        /// </summary>
        /// <remarks>
        /// Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DossierlijnGetInfo200Response</returns>
        System.Threading.Tasks.Task<DossierlijnGetInfo200Response> DossierlijnGetInfoAsync(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Dossierlijn/GetInfo
        /// </summary>
        /// <remarks>
        /// Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </remarks>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DossierlijnGetInfo200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<DossierlijnGetInfo200Response>> DossierlijnGetInfoWithHttpInfoAsync(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDossierlijnApi : IDossierlijnApiSync, IDossierlijnApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DossierlijnApi : IDossierlijnApi
    {
        private TagorClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DossierlijnApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DossierlijnApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DossierlijnApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DossierlijnApi(string basePath)
        {
            this.Configuration = TagorClient.Client.Configuration.MergeConfigurations(
                TagorClient.Client.GlobalConfiguration.Instance,
                new TagorClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DossierlijnApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DossierlijnApi(TagorClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TagorClient.Client.Configuration.MergeConfigurations(
                TagorClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TagorClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DossierlijnApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DossierlijnApi(TagorClient.Client.ISynchronousClient client, TagorClient.Client.IAsynchronousClient asyncClient, TagorClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TagorClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TagorClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TagorClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TagorClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Dossierlijn/CreateInfoLine Create an info record on a financial record
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DossierlijnCreateInfoLine200Response</returns>
        public DossierlijnCreateInfoLine200Response DossierlijnCreateInfoLine(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0)
        {
            TagorClient.Client.ApiResponse<DossierlijnCreateInfoLine200Response> localVarResponse = DossierlijnCreateInfoLineWithHttpInfo(dossierlijnCreateInfoLineRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/CreateInfoLine Create an info record on a financial record
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DossierlijnCreateInfoLine200Response</returns>
        public TagorClient.Client.ApiResponse<DossierlijnCreateInfoLine200Response> DossierlijnCreateInfoLineWithHttpInfo(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0)
        {
            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnCreateInfoLineRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnCreateInfoLine";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DossierlijnCreateInfoLine200Response>("/Dossierlijn/CreateInfoLine", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnCreateInfoLine", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Dossierlijn/CreateInfoLine Create an info record on a financial record
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DossierlijnCreateInfoLine200Response</returns>
        public async System.Threading.Tasks.Task<DossierlijnCreateInfoLine200Response> DossierlijnCreateInfoLineAsync(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            TagorClient.Client.ApiResponse<DossierlijnCreateInfoLine200Response> localVarResponse = await DossierlijnCreateInfoLineWithHttpInfoAsync(dossierlijnCreateInfoLineRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/CreateInfoLine Create an info record on a financial record
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnCreateInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DossierlijnCreateInfoLine200Response)</returns>
        public async System.Threading.Tasks.Task<TagorClient.Client.ApiResponse<DossierlijnCreateInfoLine200Response>> DossierlijnCreateInfoLineWithHttpInfoAsync(DossierlijnCreateInfoLineRequest? dossierlijnCreateInfoLineRequest = default(DossierlijnCreateInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnCreateInfoLineRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnCreateInfoLine";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DossierlijnCreateInfoLine200Response>("/Dossierlijn/CreateInfoLine", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnCreateInfoLine", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Dossierlijn/DeleteInfoLine Deletes a single info record.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PartyDeleteContactDetail200Response</returns>
        public PartyDeleteContactDetail200Response DossierlijnDeleteInfoLine(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0)
        {
            TagorClient.Client.ApiResponse<PartyDeleteContactDetail200Response> localVarResponse = DossierlijnDeleteInfoLineWithHttpInfo(dossierlijnDeleteInfoLineRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/DeleteInfoLine Deletes a single info record.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PartyDeleteContactDetail200Response</returns>
        public TagorClient.Client.ApiResponse<PartyDeleteContactDetail200Response> DossierlijnDeleteInfoLineWithHttpInfo(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0)
        {
            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnDeleteInfoLineRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnDeleteInfoLine";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PartyDeleteContactDetail200Response>("/Dossierlijn/DeleteInfoLine", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnDeleteInfoLine", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Dossierlijn/DeleteInfoLine Deletes a single info record.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PartyDeleteContactDetail200Response</returns>
        public async System.Threading.Tasks.Task<PartyDeleteContactDetail200Response> DossierlijnDeleteInfoLineAsync(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            TagorClient.Client.ApiResponse<PartyDeleteContactDetail200Response> localVarResponse = await DossierlijnDeleteInfoLineWithHttpInfoAsync(dossierlijnDeleteInfoLineRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/DeleteInfoLine Deletes a single info record.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnDeleteInfoLineRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PartyDeleteContactDetail200Response)</returns>
        public async System.Threading.Tasks.Task<TagorClient.Client.ApiResponse<PartyDeleteContactDetail200Response>> DossierlijnDeleteInfoLineWithHttpInfoAsync(DossierlijnDeleteInfoLineRequest? dossierlijnDeleteInfoLineRequest = default(DossierlijnDeleteInfoLineRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnDeleteInfoLineRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnDeleteInfoLine";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PartyDeleteContactDetail200Response>("/Dossierlijn/DeleteInfoLine", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnDeleteInfoLine", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Dossierlijn/GetInfo Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DossierlijnGetInfo200Response</returns>
        public DossierlijnGetInfo200Response DossierlijnGetInfo(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0)
        {
            TagorClient.Client.ApiResponse<DossierlijnGetInfo200Response> localVarResponse = DossierlijnGetInfoWithHttpInfo(dossierlijnGetInfoRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/GetInfo Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DossierlijnGetInfo200Response</returns>
        public TagorClient.Client.ApiResponse<DossierlijnGetInfo200Response> DossierlijnGetInfoWithHttpInfo(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0)
        {
            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnGetInfoRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnGetInfo";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DossierlijnGetInfo200Response>("/Dossierlijn/GetInfo", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnGetInfo", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Dossierlijn/GetInfo Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DossierlijnGetInfo200Response</returns>
        public async System.Threading.Tasks.Task<DossierlijnGetInfo200Response> DossierlijnGetInfoAsync(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            TagorClient.Client.ApiResponse<DossierlijnGetInfo200Response> localVarResponse = await DossierlijnGetInfoWithHttpInfoAsync(dossierlijnGetInfoRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dossierlijn/GetInfo Returns all info records on a financial record. &#x60;ttWebContext&#x60; requires a &#x60;TDOSLIJN_Id&#x60; element.
        /// </summary>
        /// <exception cref="TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dossierlijnGetInfoRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DossierlijnGetInfo200Response)</returns>
        public async System.Threading.Tasks.Task<TagorClient.Client.ApiResponse<DossierlijnGetInfo200Response>> DossierlijnGetInfoWithHttpInfoAsync(DossierlijnGetInfoRequest? dossierlijnGetInfoRequest = default(DossierlijnGetInfoRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            TagorClient.Client.RequestOptions localVarRequestOptions = new TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = dossierlijnGetInfoRequest;

            localVarRequestOptions.Operation = "DossierlijnApi.DossierlijnGetInfo";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DossierlijnGetInfo200Response>("/Dossierlijn/GetInfo", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DossierlijnGetInfo", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
