/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TagorClient.Model;
using TagorClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TagorClient.Test.Model
{
    /// <summary>
    ///  Class for testing DossierGetSub200ResponseResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DossierGetSub200ResponseResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DossierGetSub200ResponseResponse
        //private DossierGetSub200ResponseResponse instance;

        public DossierGetSub200ResponseResponseTests()
        {
            // TODO uncomment below to create an instance of DossierGetSub200ResponseResponse
            //instance = new DossierGetSub200ResponseResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DossierGetSub200ResponseResponse
        /// </summary>
        [Fact]
        public void DossierGetSub200ResponseResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DossierGetSub200ResponseResponse
            //Assert.IsType<DossierGetSub200ResponseResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DsWebContext'
        /// </summary>
        [Fact]
        public void DsWebContextTest()
        {
            // TODO unit test for the property 'DsWebContext'
        }

        /// <summary>
        /// Test the property 'DsTDOSDOSWeb'
        /// </summary>
        [Fact]
        public void DsTDOSDOSWebTest()
        {
            // TODO unit test for the property 'DsTDOSDOSWeb'
        }
    }
}
