/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Microsoft.Extensions.Logging;
using GDWInnovations.TagorClient.Client;
using GDWInnovations.TagorClient.Model;

namespace GDWInnovations.TagorClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Actions/SendMail
        /// </summary>
        /// <remarks>
        /// Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ActionsSendMail200Response</returns>
        ActionsSendMail200Response ActionsSendMail(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0);

        /// <summary>
        /// Actions/SendMail
        /// </summary>
        /// <remarks>
        /// Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ActionsSendMail200Response</returns>
        ApiResponse<ActionsSendMail200Response> ActionsSendMailWithHttpInfo(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0);
        /// <summary>
        /// Actions/SendSms
        /// </summary>
        /// <remarks>
        /// Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ActionsSendMail200Response</returns>
        ActionsSendMail200Response ActionsSendSms(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0);

        /// <summary>
        /// Actions/SendSms
        /// </summary>
        /// <remarks>
        /// Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ActionsSendMail200Response</returns>
        ApiResponse<ActionsSendMail200Response> ActionsSendSmsWithHttpInfo(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Actions/SendMail
        /// </summary>
        /// <remarks>
        /// Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionsSendMail200Response</returns>
        System.Threading.Tasks.Task<ActionsSendMail200Response> ActionsSendMailAsync(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Actions/SendMail
        /// </summary>
        /// <remarks>
        /// Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionsSendMail200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActionsSendMail200Response>> ActionsSendMailWithHttpInfoAsync(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Actions/SendSms
        /// </summary>
        /// <remarks>
        /// Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionsSendMail200Response</returns>
        System.Threading.Tasks.Task<ActionsSendMail200Response> ActionsSendSmsAsync(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Actions/SendSms
        /// </summary>
        /// <remarks>
        /// Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </remarks>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionsSendMail200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActionsSendMail200Response>> ActionsSendSmsWithHttpInfoAsync(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionsApi : IActionsApiSync, IActionsApiAsync
    {
        /// <summary>
        /// Set the logger to this service
        /// </summary>
        /// <param name="loggerFactory"></param>
        public void SetLogger(ILoggerFactory loggerFactory);   
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ActionsApi : IActionsApi
    {
        /// <summary>
        /// Set the logger to this service
        /// </summary>
        /// <param name="loggerFactory">The logger factory</param>
        public void SetLogger(ILoggerFactory loggerFactory)
        {
            this.Client.SetLogger(loggerFactory);
            this.AsynchronousClient.SetLogger(loggerFactory);
        }

        private GDWInnovations.TagorClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ActionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ActionsApi(string basePath)
        {
            this.Configuration = GDWInnovations.TagorClient.Client.Configuration.MergeConfigurations(
                GDWInnovations.TagorClient.Client.GlobalConfiguration.Instance,
                new GDWInnovations.TagorClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GDWInnovations.TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GDWInnovations.TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GDWInnovations.TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ActionsApi(GDWInnovations.TagorClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GDWInnovations.TagorClient.Client.Configuration.MergeConfigurations(
                GDWInnovations.TagorClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GDWInnovations.TagorClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GDWInnovations.TagorClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GDWInnovations.TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ActionsApi(GDWInnovations.TagorClient.Client.ISynchronousClient client, GDWInnovations.TagorClient.Client.IAsynchronousClient asyncClient, GDWInnovations.TagorClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GDWInnovations.TagorClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GDWInnovations.TagorClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GDWInnovations.TagorClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GDWInnovations.TagorClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GDWInnovations.TagorClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Actions/SendMail Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ActionsSendMail200Response</returns>
        public ActionsSendMail200Response ActionsSendMail(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0)
        {
            GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> localVarResponse = ActionsSendMailWithHttpInfo(actionsSendMailRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Actions/SendMail Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ActionsSendMail200Response</returns>
        public GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> ActionsSendMailWithHttpInfo(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0)
        {
            GDWInnovations.TagorClient.Client.RequestOptions localVarRequestOptions = new GDWInnovations.TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actionsSendMailRequest;

            localVarRequestOptions.Operation = "ActionsApi.ActionsSendMail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Pin) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Hash) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ActionsSendMail200Response>("/Actions/SendMail", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActionsSendMail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Actions/SendMail Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionsSendMail200Response</returns>
        public async System.Threading.Tasks.Task<ActionsSendMail200Response> ActionsSendMailAsync(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> localVarResponse = await ActionsSendMailWithHttpInfoAsync(actionsSendMailRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Actions/SendMail Send a mail. This endpoint will send a mail to the party entered in &#x60;TPAR_Id&#x60; if no &#x60;TPAR_Id&#x60; is passed it will send an email to the address passed in &#x60;Emailadres&#x60;. If &#x60;TDOS_Id&#x60; is passed the mail is only send if the file exists. When both &#x60;TDOS_Id&#x60; and &#x60;TPAR_Id&#x60; are passed, the party has to be a party connected to the file for the check to pass.   _&#x60;Parameter 569&#x60; has to contain the 117 connection string. In the office management screen a mailserver and mail template has to be configured. Logging about connection with the SMTP server can be found on c:\\temp\\YYYY\\MM\\DD\\socketmail.log on the 117 server._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendMailRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionsSendMail200Response)</returns>
        public async System.Threading.Tasks.Task<GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response>> ActionsSendMailWithHttpInfoAsync(ActionsSendMailRequest? actionsSendMailRequest = default(ActionsSendMailRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GDWInnovations.TagorClient.Client.RequestOptions localVarRequestOptions = new GDWInnovations.TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actionsSendMailRequest;

            localVarRequestOptions.Operation = "ActionsApi.ActionsSendMail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Pin) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Hash) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ActionsSendMail200Response>("/Actions/SendMail", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActionsSendMail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Actions/SendSms Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ActionsSendMail200Response</returns>
        public ActionsSendMail200Response ActionsSendSms(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0)
        {
            GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> localVarResponse = ActionsSendSmsWithHttpInfo(actionsSendSmsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Actions/SendSms Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ActionsSendMail200Response</returns>
        public GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> ActionsSendSmsWithHttpInfo(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0)
        {
            GDWInnovations.TagorClient.Client.RequestOptions localVarRequestOptions = new GDWInnovations.TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actionsSendSmsRequest;

            localVarRequestOptions.Operation = "ActionsApi.ActionsSendSms";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Pin) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Hash) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ActionsSendMail200Response>("/Actions/SendSms", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActionsSendSms", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Actions/SendSms Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionsSendMail200Response</returns>
        public async System.Threading.Tasks.Task<ActionsSendMail200Response> ActionsSendSmsAsync(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response> localVarResponse = await ActionsSendSmsWithHttpInfoAsync(actionsSendSmsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Actions/SendSms Send a text. Requires &#x60;TPAR_Id&#x60;, &#x60;Gsmnr&#x60; or both. If a &#x60;TPAR_Id&#x60; is passed and the given party already has a communication number. The text will be send to this number. If not, or if you only pass the &#x60;Gsmnr&#x60; parameter the text will be send to this number instead.   _Enter the RingRing API key in &#x60;parameter 558&#x60;. &#x60;CodeSms&#x60; can also be any TQCFG value configured in the office managment screen._
        /// </summary>
        /// <exception cref="GDWInnovations.TagorClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionsSendSmsRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionsSendMail200Response)</returns>
        public async System.Threading.Tasks.Task<GDWInnovations.TagorClient.Client.ApiResponse<ActionsSendMail200Response>> ActionsSendSmsWithHttpInfoAsync(ActionsSendSmsRequest? actionsSendSmsRequest = default(ActionsSendSmsRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GDWInnovations.TagorClient.Client.RequestOptions localVarRequestOptions = new GDWInnovations.TagorClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GDWInnovations.TagorClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actionsSendSmsRequest;

            localVarRequestOptions.Operation = "ActionsApi.ActionsSendSms";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Pin) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Orng) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Hash) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (Tgr) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ActionsSendMail200Response>("/Actions/SendSms", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActionsSendSms", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}