/*
 * Tagor API
 *
 * Release date: 29/09/2022  ## REQUIREMENTS This version __requires__ Tagor >= 2.00.0000B0. Use [`Config/Info`](#operation/ConfigInfo) to get the active API version.  ## CHANGELOG - New [`Dossier/CreateAgenda`](#operation/DossierCreateAgenda) endpoint. - New return values in GetAgenda 'TJOB_Id, TJOBM_Id, TUSER_Id, Manueel and IsGeblokkeerd' - In CreateLine you can now add if the line is fixed with 'IsFixed' - In CreateLine you can now add a subarray with the intrests  ## INFO - Using the download button at the top you can import this collection of endpoints in **Postman** - In general all TQ(...)_Id fields are default fields which you can translate with the [`Code/GetDescription`](#operation/CodeGetDescription) endpoint. If you need an id to post to one of the endpoints you can use the [`Code/GetList`](#operation/CodeGetList) endpoint to get all possible values or [`Code/GetDescription`](#operation/CodeGetDescription) to get a value by code. These id's will be marked as `code id` in the documentation. - We chose to return all ids as string because these are 64bit integers which are too big for javascript to handle. - All italic text below the endpoint description is meant for people with access to Tagor. - The user needs an email address configured in Tagor for the services to work properly. - Pass the `Accept` header with `application/json` as value to have the server return errors in json format. - Most endpoints can be batched/paged by passing a `BATCH-SIZE` and `BATCH-NUMBER` record in `dsWebContext`.  # AUTHENTICATION Pass your token via an `Authorization` header like this: `Authorization: {bearer_format} {token}`.  ex: `Authorization: TGR IcoQbVw7wE...PPUPda61ET` <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.00.0000B1
 * Contact: info@organi.be
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GDWInnovations.TagorClient.Model;
using GDWInnovations.TagorClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GDWInnovations.TagorClient.Test.Model
{
    /// <summary>
    ///  Class for testing DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner
        //private DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner instance;

        public DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInnerTests()
        {
            // TODO uncomment below to create an instance of DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner
            //instance = new DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner
        /// </summary>
        [Fact]
        public void DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner
            //Assert.IsType<DsTBERICHTWebDsTBERICHTWebTtTBERICHTWebInner>(instance);
        }

        /// <summary>
        /// Test the property 'TBERICHTId'
        /// </summary>
        [Fact]
        public void TBERICHTIdTest()
        {
            // TODO unit test for the property 'TBERICHTId'
        }

        /// <summary>
        /// Test the property 'Ontvanger'
        /// </summary>
        [Fact]
        public void OntvangerTest()
        {
            // TODO unit test for the property 'Ontvanger'
        }

        /// <summary>
        /// Test the property 'TJOBId'
        /// </summary>
        [Fact]
        public void TJOBIdTest()
        {
            // TODO unit test for the property 'TJOBId'
        }

        /// <summary>
        /// Test the property 'TJOBOnderwerp'
        /// </summary>
        [Fact]
        public void TJOBOnderwerpTest()
        {
            // TODO unit test for the property 'TJOBOnderwerp'
        }

        /// <summary>
        /// Test the property 'TJOBTQSTATUSId'
        /// </summary>
        [Fact]
        public void TJOBTQSTATUSIdTest()
        {
            // TODO unit test for the property 'TJOBTQSTATUSId'
        }

        /// <summary>
        /// Test the property 'TQSTATUSId'
        /// </summary>
        [Fact]
        public void TQSTATUSIdTest()
        {
            // TODO unit test for the property 'TQSTATUSId'
        }

        /// <summary>
        /// Test the property 'TimeStampBericht'
        /// </summary>
        [Fact]
        public void TimeStampBerichtTest()
        {
            // TODO unit test for the property 'TimeStampBericht'
        }

        /// <summary>
        /// Test the property 'TimeStampStatusSinds'
        /// </summary>
        [Fact]
        public void TimeStampStatusSindsTest()
        {
            // TODO unit test for the property 'TimeStampStatusSinds'
        }

        /// <summary>
        /// Test the property 'TQRICHTINGId'
        /// </summary>
        [Fact]
        public void TQRICHTINGIdTest()
        {
            // TODO unit test for the property 'TQRICHTINGId'
        }

        /// <summary>
        /// Test the property 'Verzender'
        /// </summary>
        [Fact]
        public void VerzenderTest()
        {
            // TODO unit test for the property 'Verzender'
        }

        /// <summary>
        /// Test the property 'TJOBBericht'
        /// </summary>
        [Fact]
        public void TJOBBerichtTest()
        {
            // TODO unit test for the property 'TJOBBericht'
        }

        /// <summary>
        /// Test the property 'TPARIdVerzender'
        /// </summary>
        [Fact]
        public void TPARIdVerzenderTest()
        {
            // TODO unit test for the property 'TPARIdVerzender'
        }

        /// <summary>
        /// Test the property 'TPARIdOntvanger'
        /// </summary>
        [Fact]
        public void TPARIdOntvangerTest()
        {
            // TODO unit test for the property 'TPARIdOntvanger'
        }

        /// <summary>
        /// Test the property 'TDOSId'
        /// </summary>
        [Fact]
        public void TDOSIdTest()
        {
            // TODO unit test for the property 'TDOSId'
        }

        /// <summary>
        /// Test the property 'TQDOSSOORTId'
        /// </summary>
        [Fact]
        public void TQDOSSOORTIdTest()
        {
            // TODO unit test for the property 'TQDOSSOORTId'
        }

        /// <summary>
        /// Test the property 'TtTagWeb'
        /// </summary>
        [Fact]
        public void TtTagWebTest()
        {
            // TODO unit test for the property 'TtTagWeb'
        }
    }
}
